In [7]:
import pandas as pd

cars = pd.read_csv('cars.csv')
cars

print("Shape of cars:", cars.shape)
print("Column names:", cars.columns.tolist())

cars_6_to_10 = cars.iloc[5:10]
cars_6_to_10

result = cars_6_to_10[['Model', 'mpg', 'cyl', 'hp', 'gear']]
result

Shape of cars: (32, 12)
Column names: ['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

In [8]:

toyota = cars[cars['Model'] == 'Toyota Corolla']
toyota

pontiac = cars[cars['Model']=='Pontiac Firebird'][['Model', 'mpg', 'hp', 'wt']]
pontiac

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

In [9]:
selected_cars = cars[(cars['Model'] == 'Datsun 710') | (cars['Model'] == 'Lotus Europa') | (cars['Model'] == 'Ferrari Dino')]
[['Model', 'mpg', 'cyl', 'hp', 'gear']]

selected_cars

print ("Selected Car Shape", selected_cars.shape)

Selected Car Shape (3, 12)